In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [4]:
type(np.array(my_list))

numpy.ndarray

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [13]:
#start,stop,space
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
#start,stop,number_of_point
np.linspace(0,11,20)

array([ 0.        ,  0.57894737,  1.15789474,  1.73684211,  2.31578947,
        2.89473684,  3.47368421,  4.05263158,  4.63157895,  5.21052632,
        5.78947368,  6.36842105,  6.94736842,  7.52631579,  8.10526316,
        8.68421053,  9.26315789,  9.84210526, 10.42105263, 11.        ])

In [14]:
np.random.randint(0,15)

3

In [15]:
np.random.randint(0,15,(3,3))

array([[10,  2,  2],
       [ 6, 12,  8],
       [12,  8, 10]])

In [18]:
#to generate the same random numbers again again in the same cell
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [21]:
arr.max()

3

In [22]:
arr.min()

1

In [23]:
arr.mean()

2.0

In [24]:
#index of maximum element
arr.argmax()

2

In [25]:
#index of minimum element
arr.argmin()

0

In [26]:
len(arr)

3

In [29]:
arr.shape

(3,)

In [30]:
arr.reshape(3,1)

array([[1],
       [2],
       [3]])

In [31]:
mat=np.arange(0,100).reshape(10,10)

In [32]:
mat[5,5]

55

In [33]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
mat[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [35]:
mat[1:3,2:6]

array([[12, 13, 14, 15],
       [22, 23, 24, 25]])

In [38]:
#masking
#mat>20
my_filter=mat>20
mat[my_filter]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
       89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])